project:
  type: website
  output-dir: docs

website:
  title: "A Quarto Website"
  navbar:
    left:
      -  Assignement1.qmd
      -  reference.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
