project:
  type: website
  output-dir: docs

website:
  title: "A Quarto Website"
  navbar:
    left:
      - href: Assignement1.qmd
        text: Home
      - href: reference.qmd
        text: References

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
