project:
  type: website
  output-dir: docs

website:
  title: "A Quarto Website"
  navbar:
    left:
      - href: Assignement1.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
 